# deploying to prod without official deployments. 
name: replicate-cd

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      BASE_MODEL: 'stability-ai/sdxl'
      PROD_MODEL: 'stability-ai/sdxl'

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: what changed
      id: what-changed
      run: |
        FILES_CHANGED=$(git diff --name-only --diff-filter=AMR origin/main HEAD  | xargs)
        echo "FILES_CHANGED=$FILES_CHANGED" >> $GITHUB_ENV
        if echo "$FILES_CHANGED" | grep -q 'cog.yaml'; then
            echo "cog-push=true" >> $GITHUB_OUTPUT
          else
            echo "cog-push=false" >> $GITHUB_OUTPUT
          fi
        if ${{ contains(github.event.head_commit.message, '[cog build]') }}; then
            echo "cog-push=true" >> $GITHUB_OUTPUT
          fi

    # if cog.yaml changes - cog build and push. else - yolo build and push!
    - name: did-it-tho
      env:
        COG_PUSH: ${{ steps.what-changed.outputs.cog-push }}
      run: |
        echo "cog push?: $COG_PUSH"
        echo "changed files: $FILES_CHANGED"

    - name: setup-cog
      if: steps.what-changed.outputs.cog-push == 'true'
      uses: replicate/setup-cog@v1.0.3
      with:
        token: ${{ secrets.REPLICATE_API_TOKEN }}
        install-cuda: false
        cog-version: "v0.9.8"

    - name: cog-build
      if: steps.what-changed.outputs.cog-push == 'true'
      run: |
        cog build --use-cuda-base-image=false

    - name: cog-push
      if: steps.what-changed.outputs.cog-push == 'true'
      run: |
        cog push --use-cuda-base-image=false r8.im/"$PROD_MODEL"

    - name: install-yolo
      if: steps.what-changed.outputs.cog-push == 'false'
      run: |
        sudo curl -o /usr/local/bin/yolo -L "https://github.com/replicate/yolo/releases/latest/download/yolo_$(uname -s)_$(uname -m)"
        sudo chmod +x /usr/local/bin/yolo

    - name: yolo-push
      if: steps.what-changed.outputs.cog-push == 'false'
      env:
       REPLICATE_API_TOKEN: ${{secrets.REPLICATE_API_TOKEN}}
       SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      run: |
        echo "pushing changes from $BASE_MODEL to $PROD_MODEL"
        echo "changed files: $FILES_CHANGED"
        yolo push --base $BASE_MODEL --dest $PROD_MODEL $FILES_CHANGED
